// auto-generated by ContractResolver
// Generated: 2026-03-22T13:11:32.293Z
// Total tokens: 7

module.exports = [
    {
        symbol: "BARD",
        dex: {
            ethereum: "0xf0DB65D17e30a966C2ae6A21f6BBA71cea6e9754"
        },
        cex: {
            gateio: "BARD/USDT"
        }
    },

    {
        symbol: "COS",
        dex: {
            bsc: "0x96dd399f9c3afda1f194182f71600f1b65946501"
        },
        cex: {
            gateio: "COS/USDT"
        }
    },

    // {
    //     symbol: "LYN",
    //     dex: {
    //         ethereum: "0x302DFaF2CDbE51a18d97186A7384e87CF599877D"
    //     },
    //     cex: {
    //         gateio: "LYN/USDT"
    //     }
    // },

    {
        symbol: "SIREN",
        dex: {
            bsc: "0x997a58129890bbda032231a52ed1ddc845fc18e1"
        },
        cex: {
            gateio: "SIREN/USDT"
        }
    },

    {
        symbol: "老子",
        dex: {
            bsc: "0x1a5f9d77ca46646cd4937fd8d093f460b66f4444"
        },
        cex: {
            gateio: "老子/USDT"
        }
    }

    // {
    //     symbol: "黑马",
    //     dex: {
    //         bsc: "0xf9C6e80e9A5807A1214a79449009b48104F94444"
    //     },
    //     cex: {
    //         gateio: "黑马/USDT"
    //     }
    // }
];
